# Generated by Django 3.1.6 on 2021-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0002_auto_20210222_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La Direccion'),
        ),
    ]
